[project]
name = "tf"
description = "Python Terraform Provider framework"
license = "MIT"
keywords = ["opentofu", "terraform", "provider", "python"]
dynamic = ["version", "classifiers"]
readme = "README.md"
authors = [{name = "Hunter Fernandes", email = "hunter@hfernandes.com"}]
requires-python = '>=3.11,<4.0'
dependencies = [
  'msgpack (>=1.1.0,<2.0.0)',
  'cryptography (>43)',
  'grpcio (>=1.78.0,<2.0.0)',
  'protobuf (>=6.31.1,<7.0.0)'
]

[project.urls]
homepage = "https://github.com/hfern/tf"

[tool.poetry]
version = "1.2.0"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python",
  "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.group.dev.dependencies]
grpcio-tools = "^1.78.0"
ruff = "^0.7.2"
coverage = "^7.6.4"
pyre-check = "^0.9.23"
sphinx = "^8.1.3"
sphinx-mdinclude = "^0.6.2"
sphinx-immaterial = "^0.12.4"
myst-parser = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["tf/gen"]


[tool.ruff.lint]
extend-select = ["I"]


[tool.coverage.run]
branch = true
omit = [
    "tf/gen/*",
    "*/tests/*",
]

[tool.coverage.report]
show_missing = true
include = [
    "tf/*",
]

