# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint
      run: |
        make test-format
    - name: Test
      run: |
        make test-python
    - name: Check Types
      run: |
        make test-pyre
    - name: Test Build
      run: |
        poetry build

  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.13"]
        tf-version:
          - "opentofu@v1.11.5"
          - "opentofu@v1.10.5"
          - "opentofu@v1.9.3"
        e2e-project:
          - "mathprovider"
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      working-directory: e2e/${{ matrix.e2e-project }}
      run: |
        poetry install
    - name: Install ${{ matrix.tf-version }}
      working-directory: e2e/${{ matrix.e2e-project }}
      run: |
        poetry run e2e-tool install ${{matrix.tf-version}}
    - name: Run E2E Tests
      working-directory: e2e/${{ matrix.e2e-project }}
      run: |
        poetry run e2e-tool run --tf ${{matrix.tf-version}}
